name: Winbtop CI (Windows)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      BUILD_TYPE: Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build Process
      - name: Build (CMake if present, otherwise cl)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'

          if (Test-Path -Path "CMakeLists.txt") {
            Write-Host "Building with CMake..."
            New-Item -ItemType Directory -Force -Path build | Out-Null
            cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=$env:BUILD_TYPE
            cmake --build build --config $env:BUILD_TYPE -- /m
            $exe = Get-ChildItem -Path build -Recurse -Filter "*.exe" | Select-Object -First 1
            if (-not $exe) { throw "No exe produced by CMake build" }
            Copy-Item $exe.FullName -Destination "$PWD\winbtop.exe" -Force
          }
          else {
            Write-Host "Building with MSVC cl (direct compile)..."
            $cpps = Get-ChildItem -Path src -Recurse -Filter *.cpp | % { $_.FullName }
            if (-not $cpps) { throw "No .cpp files found under src/" }

            $clArgs = @(
              "/nologo", "/W4", "/EHsc", "/std:c++17", "/Zc:__cplusplus",
              "/DUNICODE", "/D_UNICODE",
              "/Fe:winbtop.exe"
            ) + $cpps + @(
              "psapi.lib", "advapi32.lib", "pdh.lib", "shlwapi.lib"
            )

            cl $clArgs
            if ($LASTEXITCODE -ne 0) { throw "cl build failed with exit code $LASTEXITCODE" }
            if (-not (Test-Path -Path ".\winbtop.exe")) { throw "winbtop.exe not found after cl build" }
          }

      # Some Artifacts
      - name: Upload artifact (winbtop.exe)
        uses: actions/upload-artifact@v4
        with:
          name: winbtop-exe
          path: winbtop.exe
          if-no-files-found: error
